### ISSUE TITLE
`replace_background()` doesn't need to move Rgb?

### ISSUE THREAD

**Issue by samuelvanderwaal** [silvia-odwyer/photon#105]
It seems strange that `multiple::replace_background` takes ownership of the rbg parameter instead of by reference. I looked at the source code and this doesn't seem necessary since the function just needs to read the integer values. The functionality this prohibits is creating a single Rgb value that can be reused across multiple function calls.

```rust
...
let background = Rgb::new(255, 255, 255);
let mut base1 = open_image("./layers/base1.jpeg").expect("Failed to open base1");
let mut base2 = open_image("./layers/base2.jpeg").expect("Failed to open base2");
let layer1 = open_image("./layers/layer1.jpeg").expect("Failed to open layer1");
let layer2 = open_image("./layers/layer2.jpeg").expect("Failed to open layer2");

replace_background(&mut base1, &layer1, background);
replace_background(&mut base2, &layer2, background);
 ```
 
 The second call fails because `background` has already been moved. If the function must absolutely take ownership then maybe `clone` can be implemented for the `Rgb` struct?

**Comment by samuelvanderwaal** [comment]
Simply adding a reference to the parameter compiles and solves this issue, but I'm not sure if I'm missing something else or if there's a good reason not to do that.

My fork with that one change: https://github.com/samuelvanderwaal/photon/tree/issue-105.

**Comment by silvia-odwyer** [comment]
@samuelvanderwaal Hi Samuel, thanks for letting me know about this! Indeed, the RGB color should be passed by reference instead of the function taking ownership of the parameter. If you'd like to open a pull request, I'll be sure to merge it 👍 Thanks!
