### ISSUE TITLE
Runtime Error for image with less than 4 channels

### ISSUE THREAD

**Issue by a1trl9** [silvia-odwyer/photon#11]
Hi Silvia,

For now, at first step of many functions in this project, we would try to create a `DynamicImage` instance with function `helper::dyn_image_from_raw` and it works perfectly in most circumstance. However, when I tried to pass a **grayscale** image as a base64 string, for example:

```rust
let base64_str = "iVBORw0KGgoAAAANSUhEUgAAADIAAAAcCAAAAAAG8rMrAAAEt2lUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iWE1QIENvcmUgNS41LjAiPgogPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIgogICAgeG1sbnM6ZXhpZj0iaHR0cDovL25zLmFkb2JlLmNvbS9leGlmLzEuMC8iCiAgICB4bWxuczp0aWZmPSJodHRwOi8vbnMuYWRvYmUuY29tL3RpZmYvMS4wLyIKICAgIHhtbG5zOnBob3Rvc2hvcD0iaHR0cDovL25zLmFkb2JlLmNvbS9waG90b3Nob3AvMS4wLyIKICAgIHhtbG5zOnhtcD0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLyIKICAgIHhtbG5zOnhtcE1NPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvbW0vIgogICAgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV2ZW50IyIKICAgZXhpZjpQaXhlbFhEaW1lbnNpb249IjUwIgogICBleGlmOlBpeGVsWURpbWVuc2lvbj0iMjgiCiAgIGV4aWY6Q29sb3JTcGFjZT0iNjU1MzUiCiAgIHRpZmY6SW1hZ2VXaWR0aD0iNTAiCiAgIHRpZmY6SW1hZ2VMZW5ndGg9IjI4IgogICB0aWZmOlJlc29sdXRpb25Vbml0PSIyIgogICB0aWZmOlhSZXNvbHV0aW9uPSI3Mi4wIgogICB0aWZmOllSZXNvbHV0aW9uPSI3Mi4wIgogICBwaG90b3Nob3A6Q29sb3JNb2RlPSIxIgogICBwaG90b3Nob3A6SUNDUHJvZmlsZT0iR3JleXNjYWxlIEQ1MCIKICAgeG1wOk1vZGlmeURhdGU9IjIwMjAtMDEtMTNUMjM6MTk6MTIrMDg6MDAiCiAgIHhtcDpNZXRhZGF0YURhdGU9IjIwMjAtMDEtMTNUMjM6MTk6MTIrMDg6MDAiPgogICA8eG1wTU06SGlzdG9yeT4KICAgIDxyZGY6U2VxPgogICAgIDxyZGY6bGkKICAgICAgc3RFdnQ6YWN0aW9uPSJwcm9kdWNlZCIKICAgICAgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWZmaW5pdHkgUGhvdG8gKFNlcCAyNiAyMDE5KSIKICAgICAgc3RFdnQ6d2hlbj0iMjAyMC0wMS0xM1QyMzoxOToxMiswODowMCIvPgogICAgPC9yZGY6U2VxPgogICA8L3htcE1NOkhpc3Rvcnk+CiAgPC9yZGY6RGVzY3JpcHRpb24+CiA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgo8P3hwYWNrZXQgZW5kPSJyIj8+SMh6XQAAAN1pQ0NQR3JleXNjYWxlIEQ1MAAAGJVjYGCMyUnOLWYxYGDIzSspcg9yjIyIjFJgf8LAyMDLwM0gxaCVmFxc4BgQ4MOAE3y7BlQNBJd1QWbhVocVsKSkFicD6S1AbJZcUFQCpN8AsU95SQGQzWgBZItkhwQ5A9kgNwjk5pQmQ/WCbOVJzQsNBtJSQCzD4M5QxJDKUMlQzJDMkMiQA2QrMLgwmDKA/IddnwFYnx9DPlBlMpAsAOouYshkSGfIYChh0AGKlgJNA5mTBjY7FWhqJSiM0P1ekFiUCPcVk7ExAJd2Mpkpzru2AAAACXBIWXMAAAsTAAALEwEAmpwYAAACf0lEQVQ4jVVUyXLdRgzsBsDtyYqtyFXJNf//WTlaTqLlkY/LoHOYoSSTLBJTgwaaAHr4F43tIUHQCJCQkMpMpfn0dfz+gP6+246cn6MwSRhhJEGCAEEIkpQCrOvz7rINk23ifjtCAokk3hEVJUASRKfpy90+XWxPrvP8IxLU6dhuJYKAAAFG5m9fhcmP5La8/XyNpCgKjRDBsogxGgAITrPHB2Hq1vR92Z/e1oAACEQjw1wKuHEAIbiZPf5uHMcZWK96XveIBhAFgKJSgFBEAWYe999NY1xhZcHd1OMpUC8CbBbbuiH+sBztpuR+PDz+KIyou++1JRgFsI6AuXeXb1ZGvykzNf/585/X4xJsKRoEq0Y/2DtgHt14QQ5xhYr8ens6XvfIOAGsjGhi3wOgedcPw+Dub5Dkr7fj78tq/l80Z559n0ABpHnX931H51USbF6PXNdO/97CKsROYiAE0j2iC6djSYm2bCWL4bqlhYFAm0kCFCGYhXsEZVwk0ec9M6VtR+xhgBE0WssiwMzczUjEVRCGZU8lsgBeMsgKoJFnj2hmZlTqBRCHedfyXKYvpkhZeGVlJ+KkSaoOpsV8IF8OzMPokiEqgHb2BwRJEqrT574elS4QKoSdkI/2nwWXAMC7rVCwuxcNk5JUhqGGJFr0SlAt6bgmAOD+UgYUELAQATX14/RuFmxaCygC8l4FAKgAWn3eR7kZBLxfC1Wba0pUgYSbmfNs/PkCAURsWVMQnnlORgSd9inDhxmxZ1uJmVXuVUVm/CSrZpI27OUMYtB58gAR/KDCjw8Qa77Xrp4LFCUhPif4Rc+HqmNDEPU0hE5V/prkPUzFqP44JED5P4cLQ8uMjoS3AAAAAElFTkSuQmCC";
let mut photon_image = base64_to_image(base64_str);
helpers::dyn_image_from_raw(&photon_image);

```

A runtime error raises as `ImageBuffer::from_vec(xx)` in `dyn_image_from_raw` returns `None` and `unwrap` fails.

When I recursively looked into `base64_to_image` and printed out `raw_pixels.len()`, I found for the image data above (50 x 28), `raw_pixels.len() == 1440` instead of `1440 x 4` -- looks like `load_from_memory` only returns data for one channel. Thus, `ImageBuffer::from_vec` returns `None` as expected since existing buffer isn't long enough for RGBA (See: https://docs.rs/image/0.19.0/image/struct.ImageBuffer.html#method.from_vec).

A similar error occurs when I tried to call `get_image_data` from the `PhotonImage` instance created above. As documented [here](https://developer.mozilla.org/en-US/docs/Web/API/ImageData/ImageData), array's length should be a multiple of (4 * width) or (4 * width * height), otherwise, an IndexSizeError will be thrown.

For double-check, I modified code like following as a workaround:

```rust
pub fn transform_grayscale_to_rgba(pixels: &Vec<u8>) -> Vec<u8> {
    pixels.iter()
        .flat_map(|&v| vec!(v, v, v, 255))
        .collect()
}

pub fn base64_to_image(base64: &str) -> PhotonImage {

    let base64_to_vec: Vec<u8> = base64_to_vec(base64);

    let slice = base64_to_vec.as_slice();

    let img = image::load_from_memory(slice).unwrap();
    
    let mut raw_pixels = img.raw_pixels();

    if raw_pixels.len() as u32 == img.width() * img.height() {
         raw_pixels = transform_grayscale_to_rgba(&raw_pixels);
    } 
    return PhotonImage { raw_pixels: raw_pixels, width: img.width(), height: img.height()};

}

pub fn get_image_data(&mut self) -> ImageData {
    if self.raw_pixels.len() as u32 == self.width * self.height {
        let mut pixels = helpers::transform_grayscale_to_rgba(&self.raw_pixels);
        let new_img_data = ImageData::new_with_u8_clamped_array_and_sh(Clamped(&mut pixels), self.width, self.height).unwrap();
        return new_img_data;
        }
    let new_img_data = ImageData::new_with_u8_clamped_array_and_sh(Clamped(&mut self.raw_pixels), self.width, self.height).unwrap();
    new_img_data
}

```

Both errors resolved.

I also tried some other examples (as base64 string), like:

![test_rgba_trans](https://user-images.githubusercontent.com/11512033/72274792-c4d44b00-3667-11ea-94ff-b26dc1e895cc.png)
 

It is not a grayscale image, but with only 3 channels. A same error raises.

But for a PNG type base64 string with transparent background, like:

![test_real_trans](https://user-images.githubusercontent.com/11512033/72274759-b423d500-3667-11ea-9f3a-1eea6a25d96a.png)

Everything works perfectly.

Would you mind checking my steps? I would appreciate for any feedback. Also I am happy to make a PR (for at least fixing RGB and grayscale) if it is confirmed an issue. 

PS: I think it wont be a problem for image data from HTML canvas as it by default contains 4 channels.

**Comment by silvia-odwyer** [comment]
@a1trl9 Thank you for raising this issue, and for your proposed edits, both were incredibly useful to me when investigating the source of the problem. 

It appears the image was not being converted to RGBA in the `base64_to_image` function, so I made the changes to convert to that, you'll see the commit up above.
Hopefully this fixes the issue, and let me know if anything isn't working! 
Thanks again! 😄

**Comment by a1trl9** [comment]
@silvia-odwyer just tested on my cases -- it works perfectly now!
