### ISSUE TITLE
open_image_from_bytes and image_to_bytes function always return unknown format

### ISSUE THREAD

**Issue by MichealZwen** [silvia-odwyer/photon#116]
![image](https://user-images.githubusercontent.com/37389563/144434130-99769fd8-9d16-47d3-8f5c-8cc14af8d725.png)
hi, i try to use this crate to implement a small demo, but when i use open_image_from_bytes and image_to_bytes function, alway return unknown format. can. you tell me why?

fetch image url: https://github.com/silvia-odwyer/photon/blob/master/docs/images/fuji.jpg 

![image](https://user-images.githubusercontent.com/37389563/144434885-ffbe0ac1-a2e9-42f7-a194-f948e963a593.png)

**Comment by Daggy1234** [comment]
Hey do you have  a url to the image you're opening/downloading. It would help debug!

**Comment by MichealZwen** [comment]
i find the problem. it's really an image format problem. But i encounter an another question. i find this crate depends on rayon, document, CssStyleDeclaration and so on. I want to know that can I find a way to make it webassembly format and run in native javascript environment instead of web or node?

**Comment by ext-allen-ef** [comment]
hi @MichealZwen I've also found the same issue: what I did was then depend upon image and convert that way:

```rust
use image::{DynamicImage, ImageBuffer, ImageOutputFormat};
use DynamicImage::ImageRgba8;

fn get_image_bytes(image: PhotonImage) -> Vec<u8> {
    let mut bytes = Vec::with_capacity(image.get_raw_pixels().len());
    let img_buffer = ImageBuffer::from_vec(image.get_width(), image.get_height(), image.get_raw_pixels()).unwrap();
    let dynimage = ImageRgba8(img_buffer);
    dynimage.write_to(&mut bytes, ImageOutputFormat::Png);
    bytes
}
```

**Comment by HangingClowns** [comment]
hi @MichealZwen I've also found the same issue: what I did was then depend upon image and convert that way:

```rust
use image::{DynamicImage, ImageBuffer, ImageOutputFormat};
use DynamicImage::ImageRgba8;

fn get_image_bytes(image: PhotonImage) -> Vec<u8> {
    let mut bytes = Vec::with_capacity(image.get_raw_pixels().len());
    let img_buffer = ImageBuffer::from_vec(image.get_width(), image.get_height(), image.get_raw_pixels()).unwrap();
    let dynimage = ImageRgba8(img_buffer);
    dynimage.write_to(&mut bytes, ImageOutputFormat::Png);
    bytes
}
```

**Comment by MichealZwen** [comment]
> i find the problem. it's really an image format problem. But i encounter an another question. i find this crate depends on rayon, document, CssStyleDeclaration and so on. I want to know that can I find a way to make it webassembly format and run in native javascript environment instead of web or node?
