### ISSUE TITLE
Website: Uncaught TypeError: e.oil is not a function

### ISSUE THREAD

**Issue by batisteo** [silvia-odwyer/photon#118]
In the [website](https://silvia-odwyer.github.io/photon/), after some time of iterating over the filters, it stops on the filter **`oil`** which doesn’t seem to be present in the bundle.  
Maybe its path changed?

**Comment by silvia-odwyer** [comment]
@batisteo Thanks very much for letting me know about this, it's much appreciated! 😄 I'm going to take a look and fix this soon 👍

**Comment by silvia-odwyer** [comment]
It should be fixed now, I just updated the website to reflect this also 👍 Thanks again! 😄
