### ISSUE TITLE
photon-node crashes when reading rainbow-pinwheel.jpg

### ISSUE THREAD

**Issue by bluthen** [silvia-odwyer/photon#120]
First off this is a awesome project. I hope I can contribute more.

### The issue
photon-node seems to crash when I tried to load a particular image (rainbow-pinwheel.jpg). 

There doesn't seem to be anything wrong with the image. I even tried to resave it with different image software. I realize it might not be an issue with photon but another library like image when combined with wasm.

### Replicate

Download:
[image_issue.zip](https://github.com/silvia-odwyer/photon/files/8226564/image_issue.zip)

To see it crash do the following:
```
unzip image_issue.zip
cd image_issue/node_test
npm ci
node index.js
```

You then get something like the following:

```
pre base64
replace
new from base64
wasm://wasm/003bcd4e:1


RuntimeError: unreachable
    at wasm://wasm/003bcd4e:wasm-function[840]:0xc57ff
    at wasm://wasm/003bcd4e:wasm-function[961]:0xcae35
    at wasm://wasm/003bcd4e:wasm-function[1296]:0xd1ff3
    at wasm://wasm/003bcd4e:wasm-function[1209]:0xd0e39
    at wasm://wasm/003bcd4e:wasm-function[1298]:0xd2057
    at wasm://wasm/003bcd4e:wasm-function[994]:0xcbf23
    at wasm://wasm/003bcd4e:wasm-function[805]:0xc37f0
    at wasm://wasm/003bcd4e:wasm-function[1063]:0xcde2c
    at wasm://wasm/003bcd4e:wasm-function[495]:0xab355
    at wasm://wasm/003bcd4e:wasm-function[1128]:0xcf68c
```

Edit: I know it is one image and maybe I can get arround this one, but I'm worried it will crash on a image I don't have control over.

**Comment by bluthen** [comment]
I wrote started a new wasm rust project and was able to open the image using the same code as photon with the image cargo. So I'm kind of confused.

**Comment by bluthen** [comment]
I took my small example of loading and tried to get it to crash by slowly making sure the Cargo.toml was similar. The crash happens when "rayon" is added to default feature.

**Comment by silvia-odwyer** [comment]
@bluthen Hi Russell, thanks very much for letting me know about this, it's much appreciated! 😄 I'm glad you found the solution to fixing this issue, perhaps for future photon-node builds, I will omit the rayon feature to help prevent errors like this in the future ✅
