### ISSUE TITLE
Why is there such a big difference in the processing time between photon_rs and photon?

### ISSUE THREAD

**Issue by marcus7701** [silvia-odwyer/photon#131]
Use photon_rs, alter_blue_channel use time 233ms
![Snipaste_2022-07-14_19-26-06](https://user-images.githubusercontent.com/49542737/178972173-2775bfd5-5be0-47a2-8887-50c2a58fa442.png)
on web, alter_channel, time use 13 ms
![Snipaste_2022-07-14_19-27-22](https://user-images.githubusercontent.com/49542737/178972423-7c4db5ad-aa4b-4e42-b714-00c13367ae43.png)
![Snipaste_2022-07-14_19-27-32](https://user-images.githubusercontent.com/49542737/178972442-58349e84-9443-44ac-88c8-de896464ba56.png)

@silvia-odwyer

**Comment by bluthen** [comment]
Just a guess, but have you tried optimized build of photon_rs?

**Comment by silvia-odwyer** [comment]
@marcus7701 When running the demo, be sure to add the `--release` flag to the command:

```bash
cargo run --release
```
This will ensure the build is optimized, as @bluthen mentioned, and performance can be maximized as a result.

**Comment by marcus7701** [comment]
> @marcus7701 When running the demo, be sure to add the `--release` flag to the command:
> 
> ```shell
> cargo run --release
> ```
> 
> This will ensure the build is optimized, as @bluthen mentioned, and performance can be maximized as a result.

useful thx
