### ISSUE TITLE
Speed issue with pure rust usage

### ISSUE THREAD

**Issue by Avocadocs** [silvia-odwyer/photon#144]
Hey,
I created new rust projet with photon only and I compiled it. When I run my code it takes minutes to generate image, is this normal ? 

```rust
extern crate photon_rs;
use photon_rs::native::{open_image, save_image};
use photon_rs::channels::invert;
use photon_rs::multiple::blend;
use photon_rs::Rgba::set_alpha;

fn main() {
    
    let mut albedo = open_image("GunGS_Albedo.tga.png").unwrap();
    let mut metallic = open_image("GunGS_Metallic.tga.png").unwrap();
    let mut ao = open_image("GunGS_AO.tga.png").unwrap();

    invert(&mut metallic);
    
    blend(&mut albedo, &metallic, "multiply");

    blend(&mut albedo, &ao, "multiply");

    save_image(albedo, "diffuse.png")
}

```

Thanks

**Comment by silvia-odwyer** [comment]
@Avocadocs Just wondering if you've added the `--release` flag to the build command?

**Comment by Avocadocs** [comment]
Yes it's working now, I was not using it. Sorry for that and thanks for your time :)

**Comment by silvia-odwyer** [comment]
@Avocadocs That's no problem at all, I'm glad it's working now! 🎉 Always happy to help, and if you have any other queries about using the library etc, don't hesitate to let me know! 😄
