### ISSUE TITLE
Image file size on disk

### ISSUE THREAD

**Issue by boxdox** [silvia-odwyer/photon#171]
Hi, I was looking for a way to calculate image size (estimated). I looked into the docs, but couldn't find any function that can help me out. Running on wasm.

**Comment by boxdox** [comment]
After some research, I guess we can add a function that can calculate an estimated size from the `PhotonImage` type itself. A naive way. If it's of interest to anyone, I can work on a PR

**Comment by silvia-odwyer** [comment]
@boxdox That would be great, if you're interested in making a PR, this project is always welcome to new contributions ✅
