### ISSUE TITLE
Why crop need a mutable reference to an image

### ISSUE THREAD

**Issue by dfeyer** [silvia-odwyer/photon#177]
The current signature is:

```rust
pub fn crop(
    photon_image: &mut [PhotonImage](https://docs.rs/photon-rs/latest/photon_rs/struct.PhotonImage.html),
    x1: [u32](https://doc.rust-lang.org/nightly/std/primitive.u32.html),
    y1: [u32](https://doc.rust-lang.org/nightly/std/primitive.u32.html),
    x2: [u32](https://doc.rust-lang.org/nightly/std/primitive.u32.html),
    y2: [u32](https://doc.rust-lang.org/nightly/std/primitive.u32.html)
) -> [PhotonImage](https://docs.rs/photon-rs/latest/photon_rs/struct.PhotonImage.html)
```

But inside the implementation, I don't understand why we need a mutable reference. I need to crop really big image, and can be nice the have async cropper, but with the mutability it's a bit messy.

Thanks for the clarification, and thanks for all the hard on it, amazing project

**Comment by silvia-odwyer** [comment]
@dfeyer Hi Dominique, 
Thanks for opening this issue. This has just been fixed by PR #179, and the function no longer needs a mutable reference to the image. Since the issue has been fixed, I'm going to close this ✅
