### ISSUE TITLE
Change function interacting with filesystem to use `impl AsRef<Path>` instead of `&str`

### ISSUE THREAD

**Issue by Turtyo** [silvia-odwyer/photon#191]
# Description

It is common for Rust functions interacting with the filesystem to not require `&str` (which is pretty cumbersome), but rather anything that can be referenced as a `Path` (which includes `&str`)
Examples:
- [image::open](https://docs.rs/image/latest/image/fn.open.html)
- [std::fs::read](https://doc.rust-lang.org/std/fs/fn.read.html)

# Impact
- This would likely not break anything for anyone using those functions in a Rust crate, as `str` already implements `AsRef<Path>`, see [here](https://doc.rust-lang.org/std/primitive.str.html#impl-AsRef%3CPath%3E-for-str)
- This would allow more flexibility in the future for people using those functions. I was building path using `PathBuf` the other day for example, and having to change to `&str` was a bit bothersome

# Implementation
I'm not sure, but it's likely we can just copy what is done by the examples I gave above

**Comment by silvia-odwyer** [comment]
@Turtyo Sounds great! This would be very useful for those using a `Path` instead of `&str`. And since str already implements AsRef<Path> as you mentioned, it will cover both use cases.

**Comment by silvia-odwyer** [comment]
@Turtyo I've implemented this feature, and updated the native functions to accept parameters that can be referenced as a Path. Since this is completed, I will close this issue ✅

**Comment by Turtyo** [comment]
@silvia-odwyer Thank you !
