### ISSUE TITLE
compilation to WASM not working..

### ISSUE THREAD

**Issue by elad-yosifon** [silvia-odwyer/photon#2]
`cargo build --release` does not create WASM bindings...  only `libphoton.so` file .
```
ERROR in ./js/index.js
Module not found: Error: Can't resolve '../../crate/pkg' in ???
 @ ./js/index.js 12:0-25
```
after cargo build, the `target` directory does not have a `pkg` dir, there is a `release` directory.

FYI, trying to compile from scratch using current `master` branch, cargo version `cargo 1.38.0 (23ef9a4ef 2019-08-20)`

**Comment by silvia-odwyer** [comment]
Thank you for opening this issue, Elad! 

To compile the library to WASM, you'll need the `wasm-pack` build tool. You can get it here: https://rustwasm.github.io/wasm-pack/ 

Then, once you have installed wasm-pack, move into the `crate` sub-directory and run the following command:

`wasm-pack build`

This will compile the crate to WebAssembly and output a ./pkg (equivalent to an npm module) which you can then use exactly as you would an npm module. You'll find this in the `crate` directory.

I will be updating the README and other future documentation to include this. I appreciate you taking the time to open this issue, and would like to thank you again! I'm always continually striving to improve Photon, and simplifying the build set-up, and improving the developer experience is a high priority, so updating the documentation will be a great addition; I will ensure to work on this in the coming week.

**Comment by elad-yosifon** [comment]
@silvia-odwyer sure np... will update soon

**Comment by elad-yosifon** [comment]
@silvia-odwyer wasm-pack works..  thanks!
