### ISSUE TITLE
Seam Carver

### ISSUE THREAD

**Issue by Horki** [silvia-odwyer/photon#43]
@silvia-odwyer Hi, I have included seam carver from imageproc library, which is still experimental, but in some near iteration it will get better, also I have added some small bug fixes #42

**Comment by Horki** [comment]
@silvia-odwyer bump

**Comment by silvia-odwyer** [comment]
@Horki Thanks again for your pull request #42, much appreciated 😄 Since that was merged, I'm going to close this ✅

**Comment by Horki** [comment]
@silvia-odwyer feel free to add me to contributors list :student:

**Comment by silvia-odwyer** [comment]
@Horki I just added you to the contributors list in the README 😄Let me know if you'd like to also add your GitHub username, etc.,  Thanks again for your great work on this library!

**Comment by Horki** [comment]
@silvia-odwyer 
yes please add all
