### ISSUE TITLE
Hacktober?

### ISSUE THREAD

**Issue by Horki** [silvia-odwyer/photon#47]
@silvia-odwyer is it possible to participate in [Hacktober](https://puppet.com/blog/hacktoberfest-2020/)?

**Comment by silvia-odwyer** [comment]
Yes, I've just opted this repository into Hacktoberfest :D If you submit any PRs during this time, I'll make sure to add the `hacktoberfest-accepted` label to all accepted PRs too 👍 

All contributions are welcome! Whether those are new photo filters, [adding tutorials or documentation to the guide](https://silvia-odwyer.github.io/photon/guide/), or solving some of the [issues](https://github.com/silvia-odwyer/photon/issues), they'll all be greatly appreciated.
