### ISSUE TITLE
Demo page fails to resize image

### ISSUE THREAD

**Issue by styfle** [silvia-odwyer/photon#49]
1. Visit https://silvia-odwyer.github.io/photon/demo.html
2. Click on "Resize Image" in the left navbar
3. View dev tools console

```
Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at x (demo.js:265)
    at HTMLLIElement.<anonymous> (demo.js:26)
```

Tested in Google Chrome 85.

**Comment by silvia-odwyer** [comment]
Thanks for reporting this @styfle! I've fixed the issue, so it should work now. 👍

**Comment by styfle** [comment]
@silvia-odwyer Thanks, its working now!
