### ISSUE TITLE
Which image formats are supported?

### ISSUE THREAD

**Issue by styfle** [silvia-odwyer/photon#50]
Which image formats are supported?

Can photon convert from one image format to another?

**Comment by silvia-odwyer** [comment]
Hi @styfle 
The following image formats are supported:
1. PNG
2. JPEG
3. BMP
4. ICO
5. TIFF

Yes, the library automatically converts from one image format to the other. For example, if you load a PNG file and want to export it as a JPEG or another image format, the library allows for this. Hope that answers your question, and I'll leave this issue open until I update the guide/README to include the supported image formats.  

If you have other questions or issues, don't hesitate to let me know, thanks so much! 😄

**Comment by styfle** [comment]
@silvia-odwyer 

Great, thanks for the quick response!

I would be helpful to have docs to show converting from one format to another 👍 

Another question for you: can photon change the quality of an image?
For example, [sharp](https://sharp.pixelplumbing.com/api-output) has quality option which is basically 1-100 percent, default 80.

**Comment by silvia-odwyer** [comment]
@styfle Currently there's no functionality to let photon change the quality of the image, however this is a feature that I'd like to add soon enough! Ideally, I'd like to have an output function for JPGs which takes a quality parameter.  I'm planning to have this feature available in the next release of the library.
 
Thanks again for your questions, always great to get questions or thoughts on the library! 👍

**Comment by styfle** [comment]
Wonderful, thanks! 🥇 

I created a couple feature requests (#51 and #52) so this issue can focus on documenting the existing file formats 👍 

Keep up the great work 🎉

**Comment by silvia-odwyer** [comment]
I just added the supported image formats to the repo's documentation, including the [guide ](https://silvia-odwyer.github.io/photon/guide/)and the README, so I'll close this issue ✅
