### ISSUE TITLE
Add support for webp image format

### ISSUE THREAD

**Issue by styfle** [silvia-odwyer/photon#51]
It would be great for photon to support [WebP](https://en.wikipedia.org/wiki/WebP) image format now that [most web browsers](https://caniuse.com/webp) support it.

**Comment by Daggy1234** [comment]
Hi, currently the `image` crate that photon uses for encoding and decoding of images doesn't support saving images as webp (no encoding) but cannot decode. 

https://github.com/image-rs/image/#supported-image-formats

**Comment by mirzap** [comment]
It would seem webp encoding has been implemented in `image` create
https://github.com/image-rs/image/commit/e9ccfcfc30950fa242957d881195bb495abaf649

**Comment by dtruffaut** [comment]
Very interested in this. Let us know when it works !

**Comment by RaphaelBronsveld** [comment]
Interested in this as well!

**Comment by Daggy1234** [comment]
Okey! I'll start testing webp and see how it performs.

**Comment by aliflux-omo** [comment]
Hi, is there any update on webp support?

**Comment by ccbikai** [comment]
Hope webp can be supported 

https://github.com/image-rs/image/blob/master/CHANGES.md
Version 0.24.4
New Features:

Encoding for webp is now available with the native library. This needs to be activate explicitly with the web-encoder feature.

**Comment by yangm2** [comment]
Looks like #164 resolves webp encoding
