### ISSUE TITLE
Updating Dependencies

### ISSUE THREAD

**Issue by Daggy1234** [silvia-odwyer/photon#56]
I want to use photon with the rust `image` crate. However image v0.23.10 is not compatible with photon which is using image v0.21.1. I would love to see support for the latest `image` crate with photon as it offers great gif support!

When I tried manually, there were 188 issues present. A lot of the library has changed, so someone well versed with the library would have to do it.

**Comment by silvia-odwyer** [comment]
@Daggy1234 Yes, I kept the `image` version at v0.21.1 because future versions contain significant breaking changes. However updating to v0.23.10 is definitely in the pipeline at some point, when the `image` crate contains new features which I'd like to incorporate into photon.

As to the gif support, may I ask for more info on your use case? I've been interested in adding gif support too, so I'd love to hear more about this! 😄

**Comment by Daggy1234** [comment]
Sure! 
soo I was developing python bindings for photon because I love this library

https://github.com/Daggy1234/polaroid and due to versioning, I had to use the old `Encoder and Decoder.` While my implementation isn't the best, it works albeit very slowly. With v-.23.10 the new encoder is much faster and should make gifs useable. In addition, I believe gifs are natively supported for encoding and could possibly really improve and add gif support to photon. I primarily develop image API's and frequently manipulate gifs. WIth python bindings, I hoped to incorporate the rich feature set of photon into python which has some great image libraries.  Thats about it. The new version would also considerably improve performance.

**Comment by Daggy1234** [comment]
Another key reason for a version bump is byte serialization.

Atm photon can only read and write from the fs, whereas in apps like a discord bot I am making in sereneity-rs, it makes a lot of sense to interact with buffers.

Latest image create has methods like `to_bytes` for `DynamicImage` that can greatly add some very cool Buffer functionality.

This buffer will work great for Js with nodejs Buffer as well.

I might try and start

**Comment by silvia-odwyer** [comment]
@Daggy1234 Great points there. I'm planning to update the dependencies, when time allows, as there would be a great number of features that would be added due to the update. 😄 Indeed, it would be great to make use of `to_bytes` for Node.js also, as I was also planning on implementing support for Node.js' Buffer also.

**Comment by nitsuga5124** [comment]
The outdated dependencies make this crate impossible to get compiled with nightly versions over 2020-11-22 due to https://github.com/rust-lang/rust/issues/44095 being stabilized.

**Comment by silvia-odwyer** [comment]
I've just updated the dependencies, and refactored the codebase. It has led to continued performance enhancements, and even faster execution times as expected, which is fantastic too. 😄 

I'll commit the changes and push them. ✅

**Comment by Daggy1234** [comment]
Thats great! How would you feel about new helper methods?

**Comment by silvia-odwyer** [comment]
@Daggy1234 That would be great! 👍 What helper methods do you have in mind?

**Comment by Daggy1234** [comment]
1)
 read from bytes
2) save to bytes

**Comment by nitsuga5124** [comment]
https://deps.rs/repo/github/silvia-odwyer/photon
It appears that some dependencies are still out of date, they should probably be updated too.

**Comment by silvia-odwyer** [comment]
@nitsuga5124 I'll make sure to update those too 👍

**Comment by silvia-odwyer** [comment]
@nitsuga5124 Just updated the remaining dependencies ✅ I couldn't seem to update the imageproc crate, because the latest version of that crate uses an unstable library feature, so I've kept it at version 0.21.0 for now

**Comment by Daggy1234** [comment]
This has been resolved so i'll close this then.
