### ISSUE TITLE
Gaussian blur panics on small images

### ISSUE THREAD

**Issue by Lxrd-AJ** [silvia-odwyer/photon#59]
The function `pub fn gaussian_blur(photon_image: &mut PhotonImage, radius: i32)` seems to cause a panic whenever the input image is small e.g a 10px by 10px image, especially when the width or height of the image is smaller than the radius.

The trace seems to point to either `box_blur_vertical` or `box_blur_horizontal` in conv.rs

**Comment by silvia-odwyer** [comment]
@Lxrd-AJ Thanks for opening this issue, I'm going to take a look into this and investigate the issue 👍

**Comment by silvia-odwyer** [comment]
@Lxrd-AJ This issue has now been fixed in #122, so I've closed this issue. Thanks again for opening it and letting me know about this! 👍  

Thanks @NorbertGarfield for the fix to this bug 😄 🎉
