### ISSUE TITLE
Enhancement: choosing FilterType in resize functions

### ISSUE THREAD

**Issue by elad-yosifon** [silvia-odwyer/photon#6]
@silvia-odwyer Many thanks for implementing resize, crop etc...  I'm gonna test them out in the next couple of days!

I have noticed you are using NN ("nearest- neighbor") as the resize algorithm. 
There are several use cases for using different algorithms (e.g. images with crisp curvy lines, lanczos3 is a much better choice for that...) - why should we limit it to NN exclusively? 
Luckily, there are several other algorithms that are already implemented - Triangle, CatmullRom, Gaussian, Lanczos3. (https://docs.rs/image/0.19.0/image/enum.FilterType.html).

It would be great if we can expose the `image::FilterType` enum as a function parameter, or provide an overloaded function for better control over the expected outcome.

I might be able to help out and provide a PR for this change in the next couple of days.. any concerns before I jump into it?

**Comment by silvia-odwyer** [comment]
Hi Elad, 
Thanks so much for mentioning this, I'm completely on-board, and was hoping to allow several other resize algorithms also, so now sounds like the perfect time to allow for those! 

Sure, if you'd like to provide a PR, that would be fantastic. As far as I'm aware, Rust doesn't support overloaded functions, so we could expose the `image::FilterType` enum as a function parameter instead.

Let me know if you have any questions, and thanks again!
