### ISSUE TITLE
Watermark functionality in the example is broken

### ISSUE THREAD

**Issue by lironhl** [silvia-odwyer/photon#71]
When trying out the example https://silvia-odwyer.github.io/photon/demo.html

Seems like the watermake and the watermark-js are broken
**Error in Watermark**
Uncaught TypeError: e.watermark_img_browser is not a function

**Error in Watermark JS**
Uncaught TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(CSSImageValue or HTMLImageElement or SVGImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap or OffscreenCanvas)'

**Comment by miqbalrr** [comment]
yeah me too

**Comment by silvia-odwyer** [comment]
@lironhl @miqbalrr I've just fixed this, it should be working now ✅ 👍

**Comment by silvia-odwyer** [comment]
Since this issue is resolved, I'm going to close it ✅
