### ISSUE TITLE
do wee need features cfg ?

### ISSUE THREAD

**Issue by miqbalrr** [silvia-odwyer/photon#72]
Hi!
i'm new in `rust` and also `wasm`

this is interesting project,
i want to use photon on my private module, but i don't need all the crates.

for example i only want use the `transform` crate in my project. 
so i don't have to download and compile all  crates

**Comment by Daggy1234** [comment]
Thats not possible atm. I don't think that makes sense either. A lot of the helper code thats part of the crate is used to make the transform.rs module.

**Comment by silvia-odwyer** [comment]
The issue mainly seems to be resolved, so I'll close this ✅
