### ISSUE TITLE
Docs: Need a detailed list of filters

### ISSUE THREAD

**Issue by Losses** [silvia-odwyer/photon#75]
I got following words from the readme:
![image](https://user-images.githubusercontent.com/1384036/110190490-8945a300-7e5e-11eb-8506-7e4c1aedd7ae.png)
![image](https://user-images.githubusercontent.com/1384036/110190493-8e0a5700-7e5e-11eb-9f33-7a7bbe7c6046.png)
One paragraph said there're 30+ filters, and another paragraph said there're 20+ filters.

But on the document:

![image](https://user-images.githubusercontent.com/1384036/110190514-a7130800-7e5e-11eb-9511-9521af4cf8a7.png)

There're only 10+ filters... that's a little bit weired...

**Comment by Daggy1234** [comment]
10 filters are in the top level,

clicking on the `filter` function will show you the other filters. All of them are documented.

**Comment by Losses** [comment]
Oh, cool, thanks!
