### ISSUE TITLE
Node example in the guide doesn't work

### ISSUE THREAD

**Issue by satyarohith** [silvia-odwyer/photon#82]
Example from https://silvia-odwyer.github.io/photon/guide/using-photon-node/#sample-code throws the following error.

```
➜  node example.js                   
wasm://wasm/0040e156:1


RuntimeError: unreachable
    at <anonymous>:wasm-function[886]:0xd72cf
    at <anonymous>:wasm-function[1016]:0xdcfa3
    at <anonymous>:wasm-function[1378]:0xe4a01
    at <anonymous>:wasm-function[1289]:0xe37c9
    at <anonymous>:wasm-function[1380]:0xe4a65
    at <anonymous>:wasm-function[1052]:0xde1b4
    at <anonymous>:wasm-function[850]:0xd51a3
    at <anonymous>:wasm-function[1131]:0xe047b
    at <anonymous>:wasm-function[526]:0xbbaed
    at <anonymous>:wasm-function[1199]:0xe1df2
```

**Comment by silvia-odwyer** [comment]
@satyarohith I just tested the example with the latest version of photon-node (v 3.0) and it seemed to work okay. May I ask what image is throwing this error, so I can try replicate it? Thanks so much, I'm hoping to fix this for you! 😄

**Comment by satyarohith** [comment]
Hi @silvia-odwyer. Sorry for the delay. The latest version is working as expected. Thanks! :)
